
export const PLUGIN_NAMES: Record<string, string> = {
    'o11n-core': 'Intrinsic / Core APIs',
    'o11n-plugin-activedirectory': 'Active Directory',
    'o11n-plugin-amqp': 'AMQP',
    'o11n-plugin-autodeploy': 'AutoDeploy',
    'o11n-plugin-avi': 'Avi',
    'o11n-plugin-aws': 'AWS EC2',
    'o11n-plugin-configurator': 'Configurator',
    'o11n-plugin-crypto': 'Crypto',
    'o11n-plugin-dynamictypes': 'Dynamic Types',
    'o11n-plugin-f5': 'F5 BIG-IP',
    'o11n-plugin-jsonpath': 'JsonPath',
    'o11n-plugin-lenovo': 'Lenovo XClarity Integrator',
    'o11n-plugin-mail': 'Mail',
    'o11n-plugin-net': 'Net',
    'o11n-plugin-powershell': 'PowerShell',
    'o11n-plugin-redis': 'Redis',
    'o11n-plugin-rest': 'REST API',
    'o11n-plugin-snmp': 'SNMP',
    'o11n-plugin-soap': 'SOAP API',
    'o11n-plugin-srm': 'Site Recovery Manager',
    'o11n-plugin-sql': 'SQL Database',
    'o11n-plugin-ssh': 'SSH',
    'o11n-plugin-support': 'Support',
    'o11n-plugin-vapi': 'vAPI',
    'o11n-plugin-vc': 'vCenter',
    'o11n-plugin-vcloud': 'vCloud Director',
    'o11n-plugin-vco': 'vRO Multi-Node',
    'o11n-plugin-vr': 'vSphere Replication',
    'o11n-plugin-vra': 'vRealize Automation',
    'o11n-plugin-vsan': 'vSAN',
    'o11n-plugin-vum': 'vCenter Update Manager',
    'o11n-plugin-xml': 'XML'
};
